-- Ching Tech OS Database Initialization
--
-- 注意：資料表由 Alembic migration 管理，請勿在此建立表格
-- 此檔案僅用於啟用 PostgreSQL 擴充功能（如有需要）
--
-- 使用方式：
-- 1. 取消 docker-compose.yml 中 init.sql 的註解
-- 2. 在下方加入需要的擴充功能
--
-- 範例：
-- CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
-- CREATE EXTENSION IF NOT EXISTS "pg_trgm";
