"""資料模型"""

from ching_tech_os.models.knowledge import (
    KnowledgeAttachment,
    KnowledgeCreate,
    KnowledgeIndex,
    KnowledgeListItem,
    KnowledgeListResponse,
    KnowledgeMetadata,
    KnowledgeResponse,
    KnowledgeSource,
    KnowledgeTags,
    KnowledgeUpdate,
    HistoryEntry,
    HistoryResponse,
    IndexEntry,
    TagsResponse,
    VersionResponse,
)

from ching_tech_os.models.message import (
    MessageSeverity,
    MessageSource,
    MessageCreate,
    MessageResponse,
    MessageListItem,
    MessageListResponse,
    MessageFilter,
    UnreadCountResponse,
    MarkReadRequest,
    MarkReadResponse,
    MessageNewEvent,
    UnreadCountEvent,
)

from ching_tech_os.models.login_record import (
    DeviceType,
    GeoLocation,
    DeviceInfo,
    LoginRecordCreate,
    LoginRecordResponse,
    LoginRecordListItem,
    LoginRecordListResponse,
    LoginRecordFilter,
    RecentLoginsResponse,
    LoginDeviceInfo,
)

__all__ = [
    # Knowledge
    "KnowledgeAttachment",
    "KnowledgeCreate",
    "KnowledgeIndex",
    "KnowledgeListItem",
    "KnowledgeListResponse",
    "KnowledgeMetadata",
    "KnowledgeResponse",
    "KnowledgeSource",
    "KnowledgeTags",
    "KnowledgeUpdate",
    "HistoryEntry",
    "HistoryResponse",
    "IndexEntry",
    "TagsResponse",
    "VersionResponse",
    # Message
    "MessageSeverity",
    "MessageSource",
    "MessageCreate",
    "MessageResponse",
    "MessageListItem",
    "MessageListResponse",
    "MessageFilter",
    "UnreadCountResponse",
    "MarkReadRequest",
    "MarkReadResponse",
    "MessageNewEvent",
    "UnreadCountEvent",
    # Login Record
    "DeviceType",
    "GeoLocation",
    "DeviceInfo",
    "LoginRecordCreate",
    "LoginRecordResponse",
    "LoginRecordListItem",
    "LoginRecordListResponse",
    "LoginRecordFilter",
    "RecentLoginsResponse",
    "LoginDeviceInfo",
]
