"""資料模型"""

from ching_tech_os.models.ai import (
    # Chat models
    ChatMessage,
    ChatCreate,
    ChatUpdate,
    ChatResponse,
    ChatDetailResponse,
    PromptInfo,
    SendMessageRequest,
    CompressChatRequest,
    # Prompt models
    AiPromptCreate,
    AiPromptUpdate,
    AiPromptResponse,
    AiPromptListItem,
    AiPromptListResponse,
    # Agent models
    AiAgentCreate,
    AiAgentUpdate,
    AiAgentResponse,
    AiAgentListItem,
    AiAgentListResponse,
    # Log models
    AiLogCreate,
    AiLogResponse,
    AiLogListItem,
    AiLogListResponse,
    AiLogFilter,
    AiLogStats,
    # Test models
    AiTestRequest,
    AiTestResponse,
)

from ching_tech_os.models.knowledge import (
    KnowledgeAttachment,
    KnowledgeCreate,
    KnowledgeIndex,
    KnowledgeListItem,
    KnowledgeListResponse,
    KnowledgeMetadata,
    KnowledgeResponse,
    KnowledgeSource,
    KnowledgeTags,
    KnowledgeUpdate,
    HistoryEntry,
    HistoryResponse,
    IndexEntry,
    TagsResponse,
    VersionResponse,
)

from ching_tech_os.models.message import (
    MessageSeverity,
    MessageSource,
    MessageCreate,
    MessageResponse,
    MessageListItem,
    MessageListResponse,
    MessageFilter,
    UnreadCountResponse,
    MarkReadRequest,
    MarkReadResponse,
    MessageNewEvent,
    UnreadCountEvent,
)

from ching_tech_os.models.login_record import (
    DeviceType,
    GeoLocation,
    DeviceInfo,
    LoginRecordCreate,
    LoginRecordResponse,
    LoginRecordListItem,
    LoginRecordListResponse,
    LoginRecordFilter,
    RecentLoginsResponse,
    LoginDeviceInfo,
)

__all__ = [
    # AI Chat
    "ChatMessage",
    "ChatCreate",
    "ChatUpdate",
    "ChatResponse",
    "ChatDetailResponse",
    "PromptInfo",
    "SendMessageRequest",
    "CompressChatRequest",
    # AI Prompt
    "AiPromptCreate",
    "AiPromptUpdate",
    "AiPromptResponse",
    "AiPromptListItem",
    "AiPromptListResponse",
    # AI Agent
    "AiAgentCreate",
    "AiAgentUpdate",
    "AiAgentResponse",
    "AiAgentListItem",
    "AiAgentListResponse",
    # AI Log
    "AiLogCreate",
    "AiLogResponse",
    "AiLogListItem",
    "AiLogListResponse",
    "AiLogFilter",
    "AiLogStats",
    # AI Test
    "AiTestRequest",
    "AiTestResponse",
    # Knowledge
    "KnowledgeAttachment",
    "KnowledgeCreate",
    "KnowledgeIndex",
    "KnowledgeListItem",
    "KnowledgeListResponse",
    "KnowledgeMetadata",
    "KnowledgeResponse",
    "KnowledgeSource",
    "KnowledgeTags",
    "KnowledgeUpdate",
    "HistoryEntry",
    "HistoryResponse",
    "IndexEntry",
    "TagsResponse",
    "VersionResponse",
    # Message
    "MessageSeverity",
    "MessageSource",
    "MessageCreate",
    "MessageResponse",
    "MessageListItem",
    "MessageListResponse",
    "MessageFilter",
    "UnreadCountResponse",
    "MarkReadRequest",
    "MarkReadResponse",
    "MessageNewEvent",
    "UnreadCountEvent",
    # Login Record
    "DeviceType",
    "GeoLocation",
    "DeviceInfo",
    "LoginRecordCreate",
    "LoginRecordResponse",
    "LoginRecordListItem",
    "LoginRecordListResponse",
    "LoginRecordFilter",
    "RecentLoginsResponse",
    "LoginDeviceInfo",
]
